---
title: "Lending Club Loan Data Analysis"
author: "Premal Shah"
date: "August 1, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load all the required packages
library(ggplot2)
library(readr)
library(choroplethrMaps)
library(choroplethr)
library(DescTools)
library(dplyr)
```

```{r}
setwd("C:/Users/preshah/OneDrive/Documents/Competitions/Data Analysis/LendingClubLoanData")
options(scipen = 999)
loanbook <- read_csv("data/loan.csv")
data(state.regions)
loanbook <- merge(loanbook, state.regions, by.x = "addr_state", by.y = "abb")
Desc(loanbook$loan_amnt, main = "Loan amount distribution", plotit = TRUE)
```


```{r}
loanbook$issue_d <- as.Date(gsub("^", "01-", loanbook$issue_d), format = "%d-%b-%Y")
amnt_df <- loanbook %>% select(issue_d, loan_amnt) %>% group_by(issue_d) %>% summarise(Amount = sum(loan_amnt))
ggplot(data = amnt_df, aes(x = issue_d, y = Amount)) + geom_line() + xlab("Date Issued")
```

```{r}
Desc(loanbook$loan_status, plotit = T)
ggplot(data = loanbook, aes(x = loan_status, y = loan_amnt)) + geom_boxplot(aes(fill = loan_status)) +
       theme(axis.text.x = element_blank()) + xlab("Status") + ylab("Amount")
```
How the grades of loans were changing over time
```{r}
amnt_df_grade <- loanbook %>% select(issue_d, loan_amnt, grade) %>% group_by(issue_d, grade) %>% summarise(Amount = sum(loan_amnt))

ggplot(amnt_df_grade, aes(x = issue_d, y = Amount)) + geom_area(aes(fill = grade)) + xlab("Date Issued")
```
Reason for taking a loan with Lending Club
```{r}
Desc(loanbook$purpose, main = "Loan purpose", plotit = TRUE)
Desc(loanbook$title, main = "Loan title", plotit = TRUE)
```
Default prediction
```{r}
bad_indicators <- c("Charged Off ",
                    "Default",
                    "Does not meet the credit policy. Status:Charged Off",
                    "In Grace Period", 
                    "Default Receiver", 
                    "Late (16-30 days)",
                    "Late (31-120 days)")
loanbook$is_bad <- ifelse(loanbook$loan_status %in% bad_indicators, 0, ifelse(loanbook$loan_status == "", NA, 1))
```
